### Obtener info
GET http://localhost:5000/info
Content-Type: application/json

###

### Crear usuario
POST http://localhost:5000/crear_usuario
Content-Type: application/json

{
  "nombre": "Janiel Rodriguez",
  "correo": "janiel@example.com"
}

###

### Obtener usuarios
GET http://localhost:5000/usuarios
Content-Type: application/json
